#!/usr/bin/env bash

script_name="$0"
script_dir="$(realpath "$(dirname "$0")")"

root_dir="$(realpath "$script_dir/..")"

auth_dir="$root_dir/auth"

auth_filepath="$auth_dir/htpasswd"

username="$1"

usage() {
  echo "$script_name: usage: $script_name USERNAME PASSWORD" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

remove_hash_string() {
  sed -i "/^$1:/d" "$2"
}

# check number of arguments
if [ "$#" != "1" ]; then
  exit_with_error "invalid number of arguments"
fi

remove_hash_string "$username" "$auth_filepath"
